# Generated by Django 6.1.1 on 2026-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('disease', models.CharField(max_length=100)),
                ('confidence', models.CharField(max_length=20)),
                ('treatment', models.TextField()),
                ('recovery_time', models.CharField(max_length=50)),
                ('expected_yield_loss', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
